image: alpine:latest

stages:
  - build
  - publish

before_script:
  - npm install

node:12:
  image: node:12-alpine
  stage: build
  script:
#    - npm run test
    - npm run build
    - npm run package
  artifacts:
    paths:
      - coverage/
      - public/
      - web-ext-artifacts/

publish_firefox:
  image: node:12-alpine
  stage: publish
  only:
    - tags
  script:
    - ls -l public
    - npm run publish || echo OK
