name: Delivery

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: install dependencies
        run: npm ci
      - name: build package
        run: npm run build
      - name: publish package
        run: npm run publish || echo OK
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      - name: Pack source code
        run: zip -r cpdn-source.zip scripts src .gitignore *.md *json *.js
      - name: Upload source code
        uses: actions/upload-artifact@v2
        with:
          name: source code
          path: cpdn-source.zip
