name: Integration

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: install dependencies
        run: npm ci
      - name: build package
        run: npm run build
      - name: Pack source code
        run: zip -r public/cpdn-source.zip scripts src .gitignore *.md *json *.js
      - name: Upload source code
        uses: actions/upload-artifact@v2
        with:
          name: source code
          path: public/cpdn-source.zip
